apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web-container
        image: my-web-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: STUDENT_NAME
          value: "Meenu"